# VelochatX 1.3.2
# build java version: JE 17
# author: waterwood

config-version: 1.3.2
check-update:
  enable: true
  auto-download: true

# 配置聊天输出的格式{xxx}代表替换的变量
# 在message里，这些规则也适用
# Group: 返回玩家的组别
# Prefix/Suffix: 返回玩家的前/后缀
# Server: 返回玩家所在的服务器，服务器的显示名字可以在下面的server-display来转换后再输出;
# player: 返回玩家的名字
# Message: 玩家的消息文本
# NOTE : SERVER && MESSAGE && PlayName 这三个字段是必须的，如果少了就好用默认的输出format:[{Server}]{PlayerName}: {Message}
# 支持mc的颜色格式包括 §和& 颜色代码，会覆盖原有的颜色
chat-format: "{Group}{Server}{Prefix}{Player}{Suffix} §8:§r {Message}"

# this option change plugin messages. it won't change message.yml && config.yml!
# usually config.yml && message.yml generate depending on your VCM default language.
locale: zh

# global/locale 这个选项设置在显示给玩家信息(提及，私聊等)是否根据玩家客户端还是服务器的语言显示？
# global: 依据服务器的语言显示给玩家(可以更改设置自定义的消息)
# locale: 依据玩家的客户端的语言显示玩家各种消息(无法自定义消息，只能显示内置的默认的插件消息)
player-locale: global

# 是否在终端输出所有玩家的文本
# 如果觉得服务器内存不够，可以把这个功能关闭尤其是服务器玩家在线人数特别多的时候
log-text:
  enable: true
  # 是否要转换输出到终端的文本颜色(实现和游戏中一样的效果，日志中不会显示颜色代码，不影响游戏中输出的颜色)
  convert: true

# 转换输出的服务器的显示名称
# display的键对应的必须是Velocity中的服务器名字 -> Velocity.toml -> [servers]
# proxy表示代理服务器，如Velocity;
# e.g. [Lobby]steven: hello -> [大厅服]steven: hello
server-display:
  enable: true
  display:
    lobby: "[§d大厅服§r]"
    server2: "[§2生存服§r]"
    proxy: "[§5代理服§r]"

# 是否需要在玩家离开/加入 子服务器的时候，在原服务器发送离开消息，在被加入的服务器发送加入消息
join-leave-broadcast:
  enable: true
  log-to-console: true
  send-to-all-subServer: false
  join-prefix: "§a(+)§r"
  leave-prefix: "§c(-)§r"
  player-join-message: "{Group}{Prefix}{Player}{Suffix} 加入了 {Server}"
  player-leave-message: "{Group}{Prefix}{Player}{Suffix} 离开了 {Server}"

# 是否需要在玩家离开/加入 群组服务器的时候，在原服务器发送离开消息，在被加入的服务器发送加入消息
join-leave-proxy-broadcast:
  enable: true
  log-to-console: true
  send-to-all-subServer: true
  join-prefix: "§a[+]]§r"
  leave-prefix: "§c[-]]§r"
  player-join-message: "{Group}{Prefix}{Player}{Suffix} 现在加入了 {Proxy}"
  player-leave-message: "{Group}{Prefix}{Player}{Suffix} 现在离开了 {Proxy}"

# 是否在提醒的时候给玩家大屏幕显示标题
mention-show-title:
  enable: true
  # 显示Title的时间,秒为单位，支持整数，非整数自动四舍五入。分别是淡入，停留，淡出的持续时间。
  time:
    fade-in: 1
    stay: 2
    fade-out: 1

# 为原本的玩家Tab替换，每个玩家前面加上显示当前的服务器
# interval 请注意该选项在玩家多的时候尽量设置较大的数值，玩家越多占用的资源会更大
# {online} 占位符需要子服插件支持(未来会开发)
tab-list:
  enable: true
  interval: 1000 #刷新间隔，毫秒为单位 输入0则表示不刷新
  format: "{server}{prefix}{player}{Suffix}" #显示的每行的每个玩家的tab的格式  可以参考chat的format的占位符以及服务器的占位符
  header: "欢迎加入{proxy} 当前服务器: {server}"
  footer: "全服在线人数 §8{total_online}§r | Ping: §8{ping}"

# 违禁词语,以","分隔
ban-words:
  enable: true
  log-to-console: true
  words: "操,干,日,狗,垃圾,傻逼"