# VelochatX 2.0.0
# build java version: JE 17
# author: waterwood
# Available language zh,en

# 此文件的版本，通常不需要改变，检测更新需要用到
config-version: 2.0.0
# 自动更新 / 自动下载
check-update:
  enable: true
  auto-download: true

# 配置聊天输出的格式{xxx}代表替换的变量
# 在message里，这些规则也适用
# channel: 返回玩家所在的服务器频道
# Group: 返回玩家的组别
# Prefix/Suffix: 返回玩家的前/后缀
# Server: 返回玩家所在的服务器，服务器的显示名字可以在下面的server-display来转换后再输出;
# player: 返回玩家的名字
# Message: 玩家的消息文本
# NOTE : SERVER && MESSAGE && PlayName 这三个字段是必须的，如果少了就好用默认的输出format:[{Server}]{PlayerName}: {Message}
# 支持mc的颜色格式包括 §和& 颜色代码，会覆盖原有的颜色
chat-format: "{channel}{Group}{Server}{Prefix}{Player}{Suffix} §8:§r {Message}"

# 插件消息文件的语音版本，通常依据于您的Java JVM的版本自动设置
locale: zh

# global/locale 这个选项设置在显示给玩家信息(提及，私聊等)是否根据玩家客户端还是服务器的语言显示？
# global: 依据服务器的语言显示给玩家(可以更改设置自定义的消息)
# locale: 依据玩家的客户端的语言显示玩家各种消息(无法自定义消息，只能显示内置的默认的插件消息)
player-locale: global

# 是否在终端输出所有玩家的文本
# 如果觉得服务器内存不够，可以把这个功能关闭尤其是服务器玩家在线人数特别多的时候
log-text:
  enable: true
  # 是否要转换输出到终端的文本颜色(实现和游戏中一样的效果，日志中不会显示颜色代码，不影响游戏中输出的颜色)
  convert: true

# 转换输出的服务器的显示名称
# display的键对应的必须是Velocity中的服务器名字 -> Velocity.toml -> [servers]
# proxy表示代理服务器，如Velocity;
# 如果出现 unknown 或 未知字样则表示下方缺少对应的服务器
# e.g. [Lobby]steven: hello -> [大厅服]steven: hello
server-display:
  enable: true
  proxy: "[§5代理服§r]"
  display:
    lobby: "[§d大厅服§r]"
    server1: "[§3小游戏服§r]"
    server2: "[§2生存服§r]"

# @自 1.4.0 版本加入
# 为每个服务器分组
# 一组频道可以有多个子服务器，一个服务器可以在多个频道内
# 当某个服务器在多个频道同时出现的时候 {channel} 默认替换成 首次 出现的服务器
# global 为 false 的时候则仅仅频道内的服务器消息互通
# global 被设置 true 则所有服务器的消息(不论是否在频道内)都会互通
# 若某个服务器不在频道内，则默认接入global，即全服互通，{channel} 占位符则会被替换成空字符串
channels:
  global: true
  channel-list:
    login:
      display: "[§6登录频道§r]"
      welcome:
        enable: true
        message: "欢迎加入登录频道"
      servers:
        - lobby
    games:
      display: "[§6小游戏频道§r]"
      welcome:
        enable: true
        message: "欢迎加入小游戏频道"
      servers:
        - server1
    survive:
      display: "[§6生存频道§r]"
      welcome:
        enable: true
        message: "欢迎加入生存频道"
      servers:
        - server2
    # 可以按照以上的格式往下添加多个频道(请注意格式要保持一致)

# 是否在提醒的时候给玩家大屏幕显示标题
mention-show-title:
  enable: true
  # 显示Title的时间,秒为单位，支持整数，非整数自动四舍五入。分别是淡入，停留，淡出的持续时间。
  time:
    fade-in: 1
    stay: 2
    fade-out: 1

# 为原本的玩家Tab替换，每个玩家前面加上显示当前的服务器
# interval 请注意该选项在玩家多的时候尽量设置较大的数值，玩家越多占用的资源会更大
tab-list:
  enable: true
  interval: 1000 #刷新间隔，毫秒为单位 输入0则表示不刷新
  format: "{server}{prefix}{player}{Suffix}" #显示的每行的每个玩家的tab的格式  可以参考chat的format的占位符以及服务器的占位符
  header: "欢迎加入{proxy} 当前服务器: {server}"
  footer: "在线人数 §8{online}§r / §8{total_online}§r | Ping: §8{ping}"

# 违禁词语,以","分隔
ban-words:
  enable: true
  log-to-console: true
  words: "操,干,日,狗,垃圾,傻逼"

# 是否启用玩家的跨服屏蔽功能(未来更新功能，当前版本默认启用)
# max-list 表示最多存储多少个玩家(对于超大型服务器这个值越小越好)
# 以 UUID 形式存储在数据库当中，一个玩家约 16B
ban-list:
  enable: true
  max-player: 20